# Generated by Django 4.0.3 on 2022-03-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала голосования')),
                ('finish_at', models.DateTimeField(verbose_name='Дата окончания голосования')),
                ('max_voice', models.IntegerField(verbose_name='Максимальное кол-во голосов')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
                'db_table': 'voting_table',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография персонажа')),
                ('age', models.IntegerField(verbose_name='Возраст персонажа')),
                ('brief_biography', models.TextField(max_length=500, verbose_name='Краткая биография')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='app.voting', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'voting',
            },
        ),
    ]
